server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5
  shutdown: graceful

polar:
  greeting: Welcome to the local book catalog!

spring:
  application:
    name: catalog-service
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/polardb_catalog
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
    driver-class-name: org.postgresql.Driver
  config:
    import: "optional:configserver:"
  lifecycle:
    timeout-per-shutdown-phase: 15s


management:
  endpoints:
    web:
      exposure:
        include: refresh